pub mod controls;
pub mod explorer;
pub mod hit;
pub mod logo;
pub mod palette;
pub mod selection;
pub mod shell;
pub mod state;
pub mod tabs;
pub mod welcome;

pub use controls::{Edge, WindowControl, control_at, control_rect, is_drag_handle, resize_edge};
pub use explorer::tree;
pub use hit::{buffer_point, explorer_header_height, explorer_row};
pub use logo::{Mark, clear_space, mark};
pub use palette::{Action, PaletteView};
pub use selection::{Band, bands};
pub use shell::draw;
pub use state::{CodeMetrics, EditorView, FileEntry, Tab, VisibleText};
pub use tabs::TabHit;
pub use welcome::{RecentEntry, Target, WelcomeView};
