[package]
name = "crc-app"
description = "The CRC Code editor."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "crc_app"
path = "src/lib.rs"

[[bin]]
name = "crc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
crc-config = { path = "../crc-config" }
crc-core = { path = "../crc-core" }
crc-editor = { path = "../crc-editor" }
crc-syntax = { path = "../crc-syntax" }
crc-text = { path = "../crc-text" }
crc-theme = { path = "../crc-theme" }
crc-ui = { path = "../crc-ui" }
rfd = { version = "0.16", default-features = false, features = ["xdg-portal", "tokio"] }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
winit = "0.30.13"

[dev-dependencies]
png = "0.18.1"
