[package]
name = "crc-app"
description = "The CRC Code editor."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "crc_app"
path = "src/lib.rs"

[[bin]]
name = "crc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
arboard = { version = "3.6.1", default-features = false }
crc-agent = { version = "0.1.0", path = "../crc-agent" }
crc-config = { path = "../crc-config" }
crc-core = { path = "../crc-core" }
crc-editor = { path = "../crc-editor" }
crc-syntax = { path = "../crc-syntax" }
crc-term = { version = "0.1.0", path = "../crc-term" }
crc-text = { version = "0.1.0", path = "../crc-text" }
crc-theme = { path = "../crc-theme" }
crc-ui = { path = "../crc-ui" }
rfd = { version = "0.16", default-features = false, features = ["xdg-portal", "tokio"] }
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
winit = "0.30.13"

[dev-dependencies]
png = "0.18.1"

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61.2", default-features = false, features = ["Win32_System_Console"] }
